apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-soktmbfh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-soktmbfh 
  name: go-soktmbfh
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-soktmbfh
    weight: 100 
